//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Library_Management
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class libraryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new libraryEntities object using the connection string found in the 'libraryEntities' section of the application configuration file.
        /// </summary>
        public libraryEntities() : base("name=libraryEntities", "libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new libraryEntities object.
        /// </summary>
        public libraryEntities(string connectionString) : base(connectionString, "libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new libraryEntities object.
        /// </summary>
        public libraryEntities(EntityConnection connection) : base(connection, "libraryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<book_entry> book_entry
        {
            get
            {
                if ((_book_entry == null))
                {
                    _book_entry = base.CreateObjectSet<book_entry>("book_entry");
                }
                return _book_entry;
            }
        }
        private ObjectSet<book_entry> _book_entry;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<bookissue> bookissues
        {
            get
            {
                if ((_bookissues == null))
                {
                    _bookissues = base.CreateObjectSet<bookissue>("bookissues");
                }
                return _bookissues;
            }
        }
        private ObjectSet<bookissue> _bookissues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student_entry> student_entry
        {
            get
            {
                if ((_student_entry == null))
                {
                    _student_entry = base.CreateObjectSet<student_entry>("student_entry");
                }
                return _student_entry;
            }
        }
        private ObjectSet<student_entry> _student_entry;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the book_entry EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobook_entry(book_entry book_entry)
        {
            base.AddObject("book_entry", book_entry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the bookissues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobookissues(bookissue bookissue)
        {
            base.AddObject("bookissues", bookissue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the student_entry EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudent_entry(student_entry student_entry)
        {
            base.AddObject("student_entry", student_entry);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libraryModel", Name="book_entry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class book_entry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new book_entry object.
        /// </summary>
        /// <param name="bookid">Initial value of the bookid property.</param>
        public static book_entry Createbook_entry(global::System.Int32 bookid)
        {
            book_entry book_entry = new book_entry();
            book_entry.bookid = bookid;
            return book_entry;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bookid
        {
            get
            {
                return _bookid;
            }
            set
            {
                if (_bookid != value)
                {
                    OnbookidChanging(value);
                    ReportPropertyChanging("bookid");
                    _bookid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bookid");
                    OnbookidChanged();
                }
            }
        }
        private global::System.Int32 _bookid;
        partial void OnbookidChanging(global::System.Int32 value);
        partial void OnbookidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auther1
        {
            get
            {
                return _auther1;
            }
            set
            {
                Onauther1Changing(value);
                ReportPropertyChanging("auther1");
                _auther1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auther1");
                Onauther1Changed();
            }
        }
        private global::System.String _auther1;
        partial void Onauther1Changing(global::System.String value);
        partial void Onauther1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String auther2
        {
            get
            {
                return _auther2;
            }
            set
            {
                Onauther2Changing(value);
                ReportPropertyChanging("auther2");
                _auther2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("auther2");
                Onauther2Changed();
            }
        }
        private global::System.String _auther2;
        partial void Onauther2Changing(global::System.String value);
        partial void Onauther2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subject
        {
            get
            {
                return _subject;
            }
            set
            {
                OnsubjectChanging(value);
                ReportPropertyChanging("subject");
                _subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("subject");
                OnsubjectChanged();
            }
        }
        private global::System.String _subject;
        partial void OnsubjectChanging(global::System.String value);
        partial void OnsubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publisher
        {
            get
            {
                return _publisher;
            }
            set
            {
                OnpublisherChanging(value);
                ReportPropertyChanging("publisher");
                _publisher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("publisher");
                OnpublisherChanged();
            }
        }
        private global::System.String _publisher;
        partial void OnpublisherChanging(global::System.String value);
        partial void OnpublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Int32> _price;
        partial void OnpriceChanging(Nullable<global::System.Int32> value);
        partial void OnpriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libraryModel", Name="bookissue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bookissue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new bookissue object.
        /// </summary>
        /// <param name="bookissueid">Initial value of the bookissueid property.</param>
        public static bookissue Createbookissue(global::System.Int32 bookissueid)
        {
            bookissue bookissue = new bookissue();
            bookissue.bookissueid = bookissueid;
            return bookissue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bookissueid
        {
            get
            {
                return _bookissueid;
            }
            set
            {
                if (_bookissueid != value)
                {
                    OnbookissueidChanging(value);
                    ReportPropertyChanging("bookissueid");
                    _bookissueid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bookissueid");
                    OnbookissueidChanged();
                }
            }
        }
        private global::System.Int32 _bookissueid;
        partial void OnbookissueidChanging(global::System.Int32 value);
        partial void OnbookissueidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String doi
        {
            get
            {
                return _doi;
            }
            set
            {
                OndoiChanging(value);
                ReportPropertyChanging("doi");
                _doi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("doi");
                OndoiChanged();
            }
        }
        private global::System.String _doi;
        partial void OndoiChanging(global::System.String value);
        partial void OndoiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> stdid
        {
            get
            {
                return _stdid;
            }
            set
            {
                OnstdidChanging(value);
                ReportPropertyChanging("stdid");
                _stdid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stdid");
                OnstdidChanged();
            }
        }
        private Nullable<global::System.Int32> _stdid;
        partial void OnstdidChanging(Nullable<global::System.Int32> value);
        partial void OnstdidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mname
        {
            get
            {
                return _mname;
            }
            set
            {
                OnmnameChanging(value);
                ReportPropertyChanging("mname");
                _mname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mname");
                OnmnameChanged();
            }
        }
        private global::System.String _mname;
        partial void OnmnameChanging(global::System.String value);
        partial void OnmnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String classes
        {
            get
            {
                return _classes;
            }
            set
            {
                OnclassesChanging(value);
                ReportPropertyChanging("classes");
                _classes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("classes");
                OnclassesChanged();
            }
        }
        private global::System.String _classes;
        partial void OnclassesChanging(global::System.String value);
        partial void OnclassesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bookid
        {
            get
            {
                return _bookid;
            }
            set
            {
                OnbookidChanging(value);
                ReportPropertyChanging("bookid");
                _bookid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bookid");
                OnbookidChanged();
            }
        }
        private Nullable<global::System.Int32> _bookid;
        partial void OnbookidChanging(Nullable<global::System.Int32> value);
        partial void OnbookidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publisher
        {
            get
            {
                return _publisher;
            }
            set
            {
                OnpublisherChanging(value);
                ReportPropertyChanging("publisher");
                _publisher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("publisher");
                OnpublisherChanged();
            }
        }
        private global::System.String _publisher;
        partial void OnpublisherChanging(global::System.String value);
        partial void OnpublisherChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="libraryModel", Name="student_entry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student_entry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student_entry object.
        /// </summary>
        /// <param name="stdid">Initial value of the stdid property.</param>
        public static student_entry Createstudent_entry(global::System.Int32 stdid)
        {
            student_entry student_entry = new student_entry();
            student_entry.stdid = stdid;
            return student_entry;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stdid
        {
            get
            {
                return _stdid;
            }
            set
            {
                if (_stdid != value)
                {
                    OnstdidChanging(value);
                    ReportPropertyChanging("stdid");
                    _stdid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stdid");
                    OnstdidChanged();
                }
            }
        }
        private global::System.Int32 _stdid;
        partial void OnstdidChanging(global::System.Int32 value);
        partial void OnstdidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String doe
        {
            get
            {
                return _doe;
            }
            set
            {
                OndoeChanging(value);
                ReportPropertyChanging("doe");
                _doe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("doe");
                OndoeChanged();
            }
        }
        private global::System.String _doe;
        partial void OndoeChanging(global::System.String value);
        partial void OndoeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mname
        {
            get
            {
                return _mname;
            }
            set
            {
                OnmnameChanging(value);
                ReportPropertyChanging("mname");
                _mname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mname");
                OnmnameChanged();
            }
        }
        private global::System.String _mname;
        partial void OnmnameChanging(global::System.String value);
        partial void OnmnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private global::System.String _class;
        partial void OnclassChanging(global::System.String value);
        partial void OnclassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mobno
        {
            get
            {
                return _mobno;
            }
            set
            {
                OnmobnoChanging(value);
                ReportPropertyChanging("mobno");
                _mobno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mobno");
                OnmobnoChanged();
            }
        }
        private global::System.String _mobno;
        partial void OnmobnoChanging(global::System.String value);
        partial void OnmobnoChanged();

        #endregion

    
    }

    #endregion

    
}
